name: RustSleep
version: 3.0.0
main: com.fz.rustsleep.RustSleep
api-version: 1.21
authors: [FZ]
description: Professional Rust-like offline body system
depend: [PacketEvents]
softdepend: [SkinsRestorer, WorldGuard]
